server:
  port: 8085
spring:
  application:
    name: product-service
  datasource:
    url: "jdbc:mysql://localhost:3306/product_db"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}


